package soil.playground.style

// NOTE: This code is auto-generated from the Material Design Theme Builder.
// https://m3.material.io/theme-builder#/custom

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF855400)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFDDB7)
val md_theme_light_onPrimaryContainer = Color(0xFF2A1700)
val md_theme_light_secondary = Color(0xFF715A41)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFCDDBD)
val md_theme_light_onSecondaryContainer = Color(0xFF281805)
val md_theme_light_tertiary = Color(0xFF54643D)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD7E9B9)
val md_theme_light_onTertiaryContainer = Color(0xFF121F02)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1F1B16)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1F1B16)
val md_theme_light_surfaceVariant = Color(0xFFF1E0D0)
val md_theme_light_onSurfaceVariant = Color(0xFF504539)
val md_theme_light_outline = Color(0xFF827568)
val md_theme_light_inverseOnSurface = Color(0xFFF9EFE7)
val md_theme_light_inverseSurface = Color(0xFF352F2A)
val md_theme_light_inversePrimary = Color(0xFFFFB95E)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF855400)
val md_theme_light_outlineVariant = Color(0xFFD4C4B5)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB95E)
val md_theme_dark_onPrimary = Color(0xFF472A00)
val md_theme_dark_primaryContainer = Color(0xFF653E00)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFDDB7)
val md_theme_dark_secondary = Color(0xFFDFC2A2)
val md_theme_dark_onSecondary = Color(0xFF3F2D17)
val md_theme_dark_secondaryContainer = Color(0xFF57432B)
val md_theme_dark_onSecondaryContainer = Color(0xFFFCDDBD)
val md_theme_dark_tertiary = Color(0xFFBBCD9E)
val md_theme_dark_onTertiary = Color(0xFF273513)
val md_theme_dark_tertiaryContainer = Color(0xFF3C4C28)
val md_theme_dark_onTertiaryContainer = Color(0xFFD7E9B9)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1F1B16)
val md_theme_dark_onBackground = Color(0xFFEBE1D9)
val md_theme_dark_surface = Color(0xFF1F1B16)
val md_theme_dark_onSurface = Color(0xFFEBE1D9)
val md_theme_dark_surfaceVariant = Color(0xFF504539)
val md_theme_dark_onSurfaceVariant = Color(0xFFD4C4B5)
val md_theme_dark_outline = Color(0xFF9C8E80)
val md_theme_dark_inverseOnSurface = Color(0xFF1F1B16)
val md_theme_dark_inverseSurface = Color(0xFFEBE1D9)
val md_theme_dark_inversePrimary = Color(0xFF855400)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB95E)
val md_theme_dark_outlineVariant = Color(0xFF504539)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF82540E)
